matrix:
  include:
    - os: osx
      osx_image: xcode9
      env: SWIFT_VERSION=4.0
    - os: osx
      osx_image: xcode9.1
      env: SWIFT_VERSION=4.0
    - os: linux
      env: SWIFT_VERSION=4.0
language: generic
sudo: required
dist: trusty
install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
- swift test
