matrix:
  include:
    - os: osx
      osx_image: xcode9.3
      env: SWIFT_VERSION=4.1
    - os: linux
      env: SWIFT_VERSION=4.1
language: generic
sudo: required
dist: trusty
install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
- swift test
